Sherlock/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sherlock.Controllers.Base;
using Sherlock.Data;
using Sherlock.Data.Models;

namespace Sherlock.Controllers
{
    [Authorize(Roles = "Superadmin")]
    public class CustomersController : BaseController
    {
        public CustomersController(SherlockContext context, IDataRepository repository) : base(context, repository) { }

        // GET: Customer
        public async Task<IActionResult> Index(int? pageNumber)
        {
            int pageSize = 10;

            var customers = _context.Customers;

            return View(await PaginatedList<Customer>.CreateAsync(customers.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Customer/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Customer = await _context.Customers.FindAsync(id);
            if (Customer == null)
            {
                return NotFound();
            }

            ViewBag.Roles = await _context.Roles.ToListAsync();
            return View(Customer);
        }

        // GET: Customer/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customer/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CustomerID,CustomerName,ContactName,ContactNumber,ContactEmail")] Customer Customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(Customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(Customer);
        }

        // GET: Customer/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Customer = await _context.Customers.FindAsync(id);
            if (Customer == null)
            {
                return NotFound();
            }
            return View(Customer);
        }

        // POST: Customer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("CustomerID,CustomerName,ContactName,ContactNumber,ContactEmail")] Customer Customer)
        {
            if (id != Customer.CustomerID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(Customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(Customer.CustomerID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(Customer);
        }

        // GET: Customer/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Customer Customer = await _context.Customers.FindAsync(id);
            if (Customer == null)
            {
                return NotFound();
            }

            return View(Customer);
        }

        // POST: Customer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var Customer = await _context.Customers.FindAsync(id);
            _context.Customers.Remove(Customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(long id)
        {
            return _context.Customers.Any(e => e.CustomerID == id);
        }
    }
}

Sherlock/Controllers/HelpCenterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sherlock.Controllers.Base;
using Sherlock.Data;
using Sherlock.Data.Models;

namespace Sherlock.Controllers
{
    public class HelpCenterController : BaseController
    {
        public HelpCenterController(SherlockContext context, IDataRepository repository) : base(context, repository) { }

        // GET: HelpCenter
        public async Task<IActionResult> Index(long? projectID, int? pageNumber)
        {
            if (projectID == null)
            {
                return NotFound();
            }

            int pageSize = 10;

            var helpCenters = _context
                .HelpCenters
                .Include(f => f.Project)
                .Where(f => f.Project.ProjectID == projectID);

            return View(await PaginatedList<HelpCenter>.CreateAsync(helpCenters.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: HelpCenter/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var helpCenter = await _context.HelpCenters.FindAsync(id);
            if (helpCenter == null)
            {
                return NotFound();
            }

            return View(helpCenter);
        }

        // GET: HelpCenter/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: HelpCenter/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("HelpCenterID,Description")] HelpCenter helpCenter)
        {
            if (ModelState.IsValid)
            {
                _context.Add(helpCenter);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(helpCenter);
        }

        // GET: HelpCenter/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var helpCenter = await _context.HelpCenters.FindAsync(id);
            if (helpCenter == null)
            {
                return NotFound();
            }
            return View(helpCenter);
        }

        // POST: HelpCenter/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("HelpCenterID,Description")] HelpCenter helpCenter)
        {
            if (id != helpCenter.HelpCenterID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(helpCenter);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HelpCenterExists(helpCenter.HelpCenterID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(helpCenter);
        }

        // GET: HelpCenter/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            HelpCenter helpCenter = await _context.HelpCenters.FindAsync(id);
            if (helpCenter == null)
            {
                return NotFound();
            }

            return View(helpCenter);
        }

        // POST: HelpCenter/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var helpCenter = await _context.HelpCenters.FindAsync(id);
            _context.HelpCenters.Remove(helpCenter);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HelpCenterExists(long id)
        {
            return _context.HelpCenters.Any(e => e.HelpCenterID == id);
        }
    }
}

Sherlock/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sherlock.Controllers.Base;
using Sherlock.Data;
using Sherlock.Data.Models;
using Microsoft.AspNetCore.Http;

namespace Sherlock.Controllers
{
    [Authorize(Roles = "Admin,Superadmin")]
    public class ProjectsController : BaseController
    {
        public ProjectsController(SherlockContext context, IDataRepository repository) : base(context, repository) { }

        // GET: Projects
        public async Task<IActionResult> Index(int? pageNumber)
        {
            int pageSize = 10;

            var projects = _context.Projects
                .Include(p => p.Stories)
                .OrderBy(p => p.ProjectID);

            if (HttpContext.Session.GetString("Project") == null && HttpContext.Session.GetString("projectID") == null)
            {
                var project = await projects.FirstOrDefaultAsync();
                HttpContext.Session.SetString("Project", project.AppName);
                HttpContext.Session.SetString("projectID", project.ProjectID.ToString());
            }

            return View(await PaginatedList<Project>.CreateAsync(projects.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Projects/Switch/5
        public async Task<IActionResult> Switch(long? projectID)
        {
            if (projectID == null)
            {
                return NotFound();
            }

            Project project = await _repository.Project(projectID.Value);
            if (project == null)
            {
                return NotFound();
            }

            HttpContext.Session.SetString("Project", project.AppName);
            HttpContext.Session.SetString("projectID", project.ProjectID.ToString());
            return RedirectToAction(nameof(Index));
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Project project = await _repository.Project(id.Value);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }


        // GET: Projects/AddMonth/5
        public async Task<IActionResult> AddMonth(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Project project = await _repository.Project(id.Value);
            if (project == null)
            {
                return NotFound();
            }

            project.LicenceEndDate = project.LicenceEndDate.AddMonths(1);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UpdateDate(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Project project = await _repository.Project(id.Value);
            if (project == null)
            {
                return NotFound();
            }

            project.LicenceEndDate = project.LicenceEndDate.AddMonths(1);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Projects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProjectID,AppName,Platform,Status,LicenceStartDate,LicenceEndDate")] Project project)
        {
            if (ModelState.IsValid)
            {
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Project project = await _repository.Project(id.Value);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("ProjectID,AppName,Platform,Status,LicenceStartDate,LicenceEndDate")] Project project)
        {
            if (id != project.ProjectID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.ProjectID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Project project = await _repository.Project(id.Value);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long projectID)
        {
            Project project = await _repository.Project(projectID);
            _context.Projects.Remove(project);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectExists(long id)
        {
            return _context.Projects.Any(e => e.ProjectID == id);
        }

    }
}

Sherlock/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sherlock</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@Context.Session.GetString("Project")</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Integrations" asp-action="Index" asp-route-projectID="@Context.Session.GetString("projectID")">Integrations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Stories" asp-action="Index" asp-route-projectID="@Context.Session.GetString("projectID")">Reports</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="HelpCenter" asp-action="Index" asp-route-projectID="@Context.Session.GetString("projectID")">Help Center</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="FAQ" asp-action="Index" asp-route-projectID="@Context.Session.GetString("projectID")">FAQs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Tags" asp-action="Index" asp-route-projectID="@Context.Session.GetString("projectID")">Tags</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Index">Projects</a>
                        </li>
                        @if (User.IsInRole("Superadmin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                        }

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Sherlock - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>